import time
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from motor.motor_asyncio import AsyncIOMotorDatabase

from app.dependencies import get_db
from app.models.ingest import IngestRequest
from app.models.context import AssembledContext, SourceDocument
from app.models.response import FormattedResponse, LLMResponse
from app.graph.workflow import get_post_llm_workflow
from app.graph.state import GraphState
from app.utils.id_generator import generate_response_id
from app.utils.logger import get_logger

logger = get_logger(__name__)
router = APIRouter()

# Fallback confidence when CHAT_A2A_WS does not supply one.
# ADK / Gemini Live does not self-report confidence the way the
# /v1/generate prompt instructs raw Gemini calls to. This is a
# conservative neutral default — tune once you have real feedback data.
DEFAULT_CONFIDENCE_SCORE = 0.7


def _validate_ingest_payload(payload: IngestRequest) -> None:
    """
    Hard validation beyond what Pydantic already enforces.
    Raises HTTPException(422) on failure — caught by FastAPI automatically
    since we raise before any DB/graph work happens.
    """
    if not payload.raw_answer or not payload.raw_answer.strip():
        raise HTTPException(
            status_code=422,
            detail="raw_answer must not be empty — nothing to validate/persist.",
        )
    if not payload.session_id or not payload.session_id.strip():
        raise HTTPException(status_code=422, detail="session_id is required.")
    if not payload.tenant_id or not payload.tenant_id.strip():
        raise HTTPException(status_code=422, detail="tenant_id is required.")

    # source_ids_used must reference IDs that actually exist in source_documents,
    # otherwise citation formatting in format_node will silently drop them anyway.
    # We don't hard-fail on mismatch — just log — since this is a soft data-quality issue.
    valid_ids = {doc.source_id for doc in payload.source_documents}
    unknown_ids = set(payload.source_ids_used) - valid_ids
    if unknown_ids:
        logger.warning(
            "ingest_unknown_source_ids",
            session_id=payload.session_id,
            unknown_ids=list(unknown_ids),
        )


def _build_synthetic_llm_response(payload: IngestRequest) -> LLMResponse:
    """
    Constructs an LLMResponse object WITHOUT calling an LLM.
    This is the object validate_node/format_node/persist_node expect —
    they only depend on its fields, not on how it was produced.
    """
    response_id = generate_response_id()

    # Only keep source_ids that are backed by an actual source_document,
    # consistent with how llm_service._parse_llm_output() validates IDs.
    valid_ids = {doc.source_id for doc in payload.source_documents}
    cleaned_source_ids = [sid for sid in payload.source_ids_used if sid in valid_ids]

    confidence = (
        payload.confidence_score
        if payload.confidence_score is not None
        else DEFAULT_CONFIDENCE_SCORE
    )
    confidence = max(0.0, min(1.0, confidence))  # clamp, same as llm_service does

    return LLMResponse(
        response_id=response_id,
        session_id=payload.session_id,
        raw_answer=payload.raw_answer,
        source_ids=cleaned_source_ids,
        confidence_score=confidence,
        model_used=payload.model_used,
        prompt_tokens=0,
        completion_tokens=0,
        latency_ms=0.0,
        created_at=datetime.now(timezone.utc),
        metadata={
            "tenant_id": payload.tenant_id,
            "user_query": payload.user_query,
            "ingested": True,  # marks this response as not LLM-generated by this service
            "num_sources_provided": len(payload.source_documents),
            "num_sources_used": len(cleaned_source_ids),
            **payload.metadata,
        },
    )


def _build_minimal_context(payload: IngestRequest) -> AssembledContext:
    """
    validate_node's confidence_scorer functions (score_citation_coverage,
    score_retrieval_relevance) need an AssembledContext with source_documents
    and user_query. We build the minimal version required — no system_prompt
    or conversation_history needed since llm_node is never invoked.
    """
    source_documents = [
        SourceDocument(
            source_id=doc.source_id,
            content=doc.content,
            score=doc.score,
            metadata=doc.metadata,
        )
        for doc in payload.source_documents
    ]

    return AssembledContext(
        session_id=payload.session_id,
        tenant_id=payload.tenant_id,
        user_query=payload.user_query,
        system_prompt="",          # unused — llm_node not invoked
        conversation_history=[],   # unused — llm_node not invoked
        source_documents=source_documents,
        memory_context=None,
        fresh_context=None,
    )


@router.post("/ingest", response_model=FormattedResponse, status_code=200)
async def ingest(
    payload: IngestRequest,
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """
    Ingests an answer ALREADY generated by an upstream system (CHAT_A2A_WS's
    ADK / Gemini Live pipeline) and runs it through validate → format → persist,
    skipping the llm_node entirely. No LLM call happens in this endpoint.

    Use this instead of POST /generate when the caller already has a final
    answer and only needs scoring, citation formatting, and persistence
    (so the response_id can later be used with POST /feedback).
    """
    request_start = time.monotonic()

    logger.info(
        "ingest_request_received",
        session_id=payload.session_id,
        tenant_id=payload.tenant_id,
        answer_length=len(payload.raw_answer),
        num_sources=len(payload.source_documents),
        confidence_provided=payload.confidence_score is not None,
    )

    try:
        _validate_ingest_payload(payload)
    except HTTPException:
        raise
    except Exception as e:
        logger.error("ingest_payload_validation_failed", error=str(e))
        raise HTTPException(status_code=422, detail=f"Invalid payload: {e}")

    try:
        llm_response = _build_synthetic_llm_response(payload)
        context = _build_minimal_context(payload)
    except Exception as e:
        logger.error("ingest_state_build_failed", session_id=payload.session_id, error=str(e))
        raise HTTPException(
            status_code=400,
            detail=f"Failed to build internal state from payload: {e}",
        )

    initial_state: GraphState = {
        "context": context,
        "session_id": payload.session_id,
        "tenant_id": payload.tenant_id,
        "llm_response": llm_response,
        "validation": None,
        "formatted": None,
        "persisted": False,
        "response_id": llm_response.response_id,
        "error": None,
        "error_node": None,
        "should_retry": False,
        "retry_count": 0,
    }

    try:
        workflow = get_post_llm_workflow()
        final_state: GraphState = await workflow.ainvoke(initial_state)
    except RuntimeError as e:
        # Workflow not initialised — a deployment/startup bug, not a client error
        logger.error("ingest_workflow_not_initialised", error=str(e))
        raise HTTPException(status_code=503, detail="Feedback service not ready. Try again shortly.")
    except Exception as e:
        logger.error(
            "ingest_workflow_invoke_failed",
            session_id=payload.session_id,
            error=str(e),
        )
        raise HTTPException(status_code=500, detail=f"Ingest pipeline failed: {e}")

    if final_state.get("error"):
        error_node = final_state.get("error_node", "unknown")
        error_msg = final_state.get("error")
        logger.error(
            "ingest_completed_with_error",
            error_node=error_node,
            error=error_msg,
            session_id=payload.session_id,
        )
        raise HTTPException(
            status_code=502,
            detail={"error": "pipeline_error", "node": error_node, "detail": error_msg},
        )

    formatted = final_state.get("formatted")
    if formatted is None:
        logger.error("ingest_produced_no_output", session_id=payload.session_id)
        raise HTTPException(
            status_code=500,
            detail="Ingest pipeline completed but produced no formatted response.",
        )

    total_latency = round((time.monotonic() - request_start) * 1000, 2)

    logger.info(
        "ingest_request_completed",
        response_id=formatted.response_id,
        session_id=payload.session_id,
        validation_passed=formatted.validation_passed,
        confidence=formatted.confidence_score,
        persisted=final_state.get("persisted", False),
        total_latency_ms=total_latency,
    )

    return formatted