from typing import Optional, Any
from pydantic import BaseModel, Field


class IngestSourceDocument(BaseModel):
    """
    Optional source document for citation formatting.
    Only needed if CHAT_A2A_WS used a KB/retrieval tool for this turn.
    """
    source_id: str
    content: str = ""
    score: float = 0.0
    metadata: dict[str, Any] = Field(default_factory=dict)


class IngestRequest(BaseModel):
    """
    Payload sent by CHAT_A2A_WS after an answer has ALREADY been
    generated by its own ADK / Gemini Live pipeline.

    This is intentionally lighter than AssembledContext used by
    POST /v1/generate — there is no system_prompt or conversation_history
    requirement here because we are NOT calling an LLM in this flow.
    """
    session_id: str
    tenant_id: str
    user_query: str
    raw_answer: str
    model_used: str = "gemini-live"

    # Optional — only present if a KB/retrieval tool was used this turn
    source_documents: list[IngestSourceDocument] = Field(default_factory=list)
    source_ids_used: list[str] = Field(default_factory=list)

    # Optional confidence — CHAT_A2A_WS's ADK pipeline does not self-report
    # confidence the way the Gemini /v1/generate prompt does. If not provided,
    # we default to a fixed heuristic in the ingest endpoint.
    confidence_score: Optional[float] = None

    # Free-form bag for SQL/Mongo tool metadata, tool_type, etc.
    # Not used by validate/format nodes directly, but persisted for debugging.
    metadata: dict[str, Any] = Field(default_factory=dict)